---
- name: RHEL10 CIS hardening via ansible-lockdown/RHEL10-CIS
  hosts: all
  become: true
  gather_facts: true
  vars:
    rhel10cis_authselect_custom_profile_name: rhel10_cis_profile
  roles:
    - RHEL10-CIS
