---
roles:
  - name: RHEL10-CIS
    src: https://github.com/ansible-lockdown/RHEL10-CIS
    scm: git
    version: main

collections:
  - name: community.general
  - name: community.crypto
  - name: ansible.posix
